{% set version = "1.0.2" %}

package:
  name: devpi-process
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/devpi-process/devpi_process-{{ version }}.tar.gz
  sha256: 412fdc7c28c38f0c9cf3487242bdb6800eeecec1dbf31f67140e59a0178a466c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - hatch-vcs >=0.4
    - hatchling >=1.25
    - pip
    - python >=3.8
  run:
    - devpi-client >=7.1
    - devpi-server >=6.12.1
    - python >=3.8
    - typing_extensions >=4.12.2

test:
  imports:
    - devpi_process
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tox-dev/devpi-process
  summary: devpi process provides a programmatic API to create and use a devpi server process
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
